# Compiles the RaplMail sandbox analyzer (frontend/wasm/raplsandbox) to a raw
# wasm32 module and inlines it, base64-encoded, into a committed JS module
# (frontend/src/lib/sandbox/wasm-blob.js). Doing the encode here means the
# normal `vite build` / installer pipeline needs NO wasm toolchain at all - it
# just bundles the generated .js like any other source file.
#
# Run this only when frontend/wasm/raplsandbox/src changes. Requires the
# wasm32-unknown-unknown target: rustup target add wasm32-unknown-unknown
$ErrorActionPreference = "Stop"
$env:PATH = "$env:USERPROFILE\.cargo\bin;$env:PATH"

$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$crate = Join-Path $root "frontend\wasm\raplsandbox"
$out = Join-Path $root "frontend\src\lib\sandbox\wasm-blob.js"

Write-Host "[1/3] cargo build --release --target wasm32-unknown-unknown"
Push-Location $crate
try {
  cargo build --release --target wasm32-unknown-unknown
  if ($LASTEXITCODE -ne 0) { throw "cargo build failed ($LASTEXITCODE)" }
} finally {
  Pop-Location
}

$wasm = Join-Path $crate "target\wasm32-unknown-unknown\release\raplsandbox.wasm"
if (-not (Test-Path $wasm)) { throw "wasm output not found: $wasm" }

Write-Host "[2/3] encoding $((Get-Item $wasm).Length) bytes to base64"
$bytes = [System.IO.File]::ReadAllBytes($wasm)
$b64 = [System.Convert]::ToBase64String($bytes)

Write-Host "[3/3] writing $out"
$outDir = Split-Path -Parent $out
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Force -Path $outDir | Out-Null }
$header = "// AUTO-GENERATED by build-wasm.ps1 from frontend/wasm/raplsandbox - do not edit by hand.`n"
$header += "// Raw wasm32 sandbox analyzer, base64-inlined so the app build needs no wasm toolchain.`n"
$content = $header + "export const WASM_B64 = `"$b64`";`n"
[System.IO.File]::WriteAllText($out, $content, (New-Object System.Text.UTF8Encoding($false)))

Write-Host "Done. Inlined wasm is $($b64.Length) base64 chars."
